import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { EventStatus, EventType } from '../../generated/prisma/client';
import { OrganizationContext } from '../../common/context/organization-context';
import { PrismaService } from '../../database/prisma.service';
import { CreateEventChecklistDto } from './dto/create-event-checklist.dto';
import { CreateEventDto } from './dto/create-event.dto';

@Injectable()
export class EventService {
  constructor(private readonly prisma: PrismaService) {}
  async create(dto: CreateEventDto, context: OrganizationContext) {
    const actor = await this.canCreate(dto, context);
    const inicio = new Date(dto.inicio); const fim = new Date(dto.fim);
    if (inicio >= fim) throw new BadRequestException('O horário de término deve ser posterior ao início');
    if (dto.blocksCampusAgenda && !actor.central) throw new ForbiddenException('Somente secretaria ou administração pode bloquear a agenda do campus');
    await this.validateReferences(dto, context); await this.assertNoConflict(dto, inicio, fim, context);
    const status = actor.central ? EventStatus.APPROVED : EventStatus.REQUESTED;
    return this.prisma.event.create({ data: { titulo: dto.titulo, descricao: dto.descricao, type: dto.type, campusId: dto.campusId, inicio, fim, responsiblePersonId: dto.responsiblePersonId, alertEnabled: dto.alertEnabled ?? false, blocksCampusAgenda: dto.blocksCampusAgenda ?? false, status, organizationId: context.organizationId, createdByUserId: context.userId, spaces: dto.spaceIds?.length ? { create: dto.spaceIds.map(spaceId => ({ spaceId })) } : undefined, serviceAreas: dto.serviceAreaIds?.length ? { create: dto.serviceAreaIds.map(serviceAreaId => ({ serviceAreaId })) } : undefined, teams: dto.teamIds?.length ? { create: dto.teamIds.map(teamId => ({ teamId })) } : undefined, history: { create: { status, changedByUserId: context.userId } } }, include: this.details });
  }
  async findAll(campusId: string | undefined, start: string | undefined, end: string | undefined, context: OrganizationContext) {
    const inicio = start || end ? { ...(start ? { gte: new Date(start) } : {}), ...(end ? { lte: new Date(end) } : {}) } : undefined;
    return this.prisma.event.findMany({ where: { organizationId: context.organizationId, ...(campusId ? { campusId } : {}), ...(inicio ? { inicio } : {}), status: { not: EventStatus.CANCELLED } }, include: this.details, orderBy: { inicio: 'asc' } });
  }
  async findOne(id: string, context: OrganizationContext) { return this.event(id, context, true); }
  async approve(id: string, context: OrganizationContext) {
    const event = await this.event(id, context); if (event.status !== EventStatus.REQUESTED) throw new BadRequestException('Somente eventos solicitados podem ser aprovados');
    await this.authorizeApproval(event.type, context); await this.assertNoConflict({ campusId: event.campusId, spaceIds: event.spaces.map(item => item.spaceId), blocksCampusAgenda: event.blocksCampusAgenda }, event.inicio, event.fim, context, event.id);
    return this.prisma.$transaction(async tx => { await tx.eventHistory.create({ data: { eventId: event.id, status: EventStatus.APPROVED, changedByUserId: context.userId } }); return tx.event.update({ where: { id: event.id }, data: { status: EventStatus.APPROVED }, include: this.details }); });
  }
  async cancel(id: string, context: OrganizationContext) {
    const event = await this.event(id, context); const user = await this.user(context);
    if (event.createdByUserId !== context.userId && !this.central(user.role)) throw new ForbiddenException('Sem permissão para cancelar este evento');
    return this.prisma.$transaction(async tx => { await tx.eventHistory.create({ data: { eventId: event.id, status: EventStatus.CANCELLED, changedByUserId: context.userId } }); return tx.event.update({ where: { id: event.id }, data: { status: EventStatus.CANCELLED }, include: this.details }); });
  }
  async addChecklist(eventId: string, dto: CreateEventChecklistDto, context: OrganizationContext) { const event = await this.event(eventId, context); await this.assertOperationalAccess(event, context); return this.prisma.eventChecklist.create({ data: { eventId: event.id, ...dto } }); }
  async toggleChecklist(id: string, context: OrganizationContext) { const item = await this.prisma.eventChecklist.findFirst({ where: { id, event: { organizationId: context.organizationId } }, include: { event: true } }); if (!item) throw new NotFoundException('Item de checklist não encontrado'); await this.assertOperationalAccess(item.event, context); return this.prisma.eventChecklist.update({ where: { id }, data: { concluido: !item.concluido, concluidoEm: item.concluido ? null : new Date() } }); }
  private async canCreate(dto: CreateEventDto, context: OrganizationContext) { const user = await this.user(context); const central = this.central(user.role) || user.role === 'PASTOR'; if (central) return { central: true }; const targets = [ ...(dto.teamIds?.length ? [{ teamId: { in: dto.teamIds } }] : []), ...(dto.serviceAreaIds?.length ? [{ serviceAreaId: { in: dto.serviceAreaIds } }] : []) ]; const leader = await this.prisma.serviceMembership.findFirst({ where: { personId: context.personId, ativo: true, role: { in: ['GENERAL_LEADER', 'CAMPUS_LEADER', 'TEAM_LEADER'] }, ...(targets.length ? { OR: targets } : {}) } }); if (!leader) throw new ForbiddenException('Somente liderança da área envolvida pode solicitar eventos'); return { central: false }; }
  private async validateReferences(dto: CreateEventDto, context: OrganizationContext) { const campus = await this.prisma.campus.findFirst({ where: { id: dto.campusId, organizationId: context.organizationId, ativo: true } }); if (!campus) throw new NotFoundException('Campus ativo não encontrado'); if (dto.responsiblePersonId && !await this.prisma.person.findFirst({ where: { id: dto.responsiblePersonId, organizationId: context.organizationId, ativo: true } })) throw new NotFoundException('Responsável não encontrado'); if (dto.spaceIds?.length) { const count = await this.prisma.space.count({ where: { id: { in: dto.spaceIds }, campusId: dto.campusId, organizationId: context.organizationId, ativo: true } }); if (count !== dto.spaceIds.length) throw new BadRequestException('Um ou mais espaços não pertencem ao campus do evento'); } if (dto.serviceAreaIds?.length) { const count = await this.prisma.serviceArea.count({ where: { id: { in: dto.serviceAreaIds }, organizationId: context.organizationId, ativo: true, OR: [{ scope: 'GLOBAL' }, { campusId: dto.campusId }] } }); if (count !== dto.serviceAreaIds.length) throw new BadRequestException('Uma ou mais áreas não estão disponíveis neste campus'); } if (dto.teamIds?.length) { const count = await this.prisma.serviceTeam.count({ where: { id: { in: dto.teamIds }, campusId: dto.campusId, organizationId: context.organizationId, ativo: true } }); if (count !== dto.teamIds.length) throw new BadRequestException('Uma ou mais equipes não pertencem ao campus do evento'); } }
  private async assertNoConflict(dto: { campusId: string; spaceIds?: string[]; blocksCampusAgenda?: boolean }, inicio: Date, fim: Date, context: OrganizationContext, exceptId?: string) { const active = { not: EventStatus.CANCELLED }; const overlap = { inicio: { lt: fim }, fim: { gt: inicio } }; const base = { organizationId: context.organizationId, campusId: dto.campusId, ...overlap, status: active, ...(exceptId ? { id: { not: exceptId } } : {}) }; const sameCampus = await this.prisma.event.findFirst({ where: base }); if (dto.blocksCampusAgenda && sameCampus) throw new BadRequestException('Há outro evento no campus neste período'); const campusBlock = await this.prisma.event.findFirst({ where: { ...base, blocksCampusAgenda: true } }); if (!dto.blocksCampusAgenda && campusBlock) throw new BadRequestException('A agenda do campus está bloqueada por outro evento neste período'); if (dto.spaceIds?.length) { const conflict = await this.prisma.eventSpace.findFirst({ where: { spaceId: { in: dto.spaceIds }, event: { organizationId: context.organizationId, ...overlap, status: active, ...(exceptId ? { id: { not: exceptId } } : {}) } } }); if (conflict) throw new BadRequestException('Um dos espaços informados já está reservado neste período'); } }
  private async event(id: string, context: OrganizationContext, full = false): Promise<any> { const event = await this.prisma.event.findFirst({ where: { id, organizationId: context.organizationId }, include: full ? { ...this.details, history: { include: { changedByUser: { select: { id: true, loginEmail: true } } }, orderBy: { createdAt: 'desc' } } } : this.details }); if (!event) throw new NotFoundException('Evento não encontrado na organização atual'); return event; }
  private async assertOperationalAccess(event: any, context: OrganizationContext) { const user = await this.user(context); if (event.createdByUserId === context.userId || this.central(user.role) || user.role === 'PASTOR') return; throw new ForbiddenException('Sem permissão para operar este evento'); }
  private async authorizeApproval(type: EventType, context: OrganizationContext) { const user = await this.user(context); const pastoral = ([EventType.PASTORAL, EventType.CONFERENCE, EventType.SPECIAL_PROGRAM] as EventType[]).includes(type); if ((pastoral && ['PASTOR', 'ADMIN', 'SUPER_ADMIN'].includes(user.role)) || (!pastoral && ['SECRETARY', 'ADMIN', 'SUPER_ADMIN', 'PASTOR'].includes(user.role))) return; throw new ForbiddenException('Sem permissão para aprovar este tipo de evento'); }
  private async user(context: OrganizationContext) { const user = await this.prisma.user.findFirst({ where: { id: context.userId, organizationId: context.organizationId } }); if (!user) throw new ForbiddenException('Usuário sem vínculo organizacional'); return user; }
  private central(role: string) { return ['SECRETARY', 'ADMIN', 'SUPER_ADMIN'].includes(role); }
  private readonly details = { campus: true, responsiblePerson: true, createdByUser: { select: { id: true, loginEmail: true } }, spaces: { include: { space: true } }, serviceAreas: { include: { serviceArea: true } }, teams: { include: { team: true } }, checklist: true } as const;
}
