import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { OrganizationContext } from '../../common/context/organization-context'; import { PrismaService } from '../../database/prisma.service'; import { CreateKidsResourceRequestDto } from './dto/create-kids-resource-request.dto'; import { CreateKidsVisualResourceDto } from './dto/create-kids-visual-resource.dto'; import { userRoleWhere } from '../../common/access/user-role.util';
@Injectable() export class KidsResourceService { constructor(private readonly prisma: PrismaService) {}
async createResource(dto:CreateKidsVisualResourceDto,c:OrganizationContext){await this.admin(c);return this.prisma.kidsVisualResource.create({data:{...dto,organizationId:c.organizationId}})}
async resources(c:OrganizationContext){return this.prisma.kidsVisualResource.findMany({where:{organizationId:c.organizationId,ativo:true},orderBy:{nome:'asc'}})}
async request(dto:CreateKidsResourceRequestDto,c:OrganizationContext){await this.kidsMember(c);const event=await this.prisma.event.findFirst({where:{id:dto.eventId,organizationId:c.organizationId,type:'WORSHIP'}});if(!event)throw new NotFoundException('Culto não encontrado');const resources=await this.prisma.kidsVisualResource.count({where:{id:{in:dto.items.map(i=>i.resourceId)},organizationId:c.organizationId,ativo:true}});if(resources!==dto.items.length)throw new BadRequestException('Recurso visual inválido');return this.prisma.kidsResourceRequest.create({data:{eventId:dto.eventId,requestedByPersonId:c.personId,organizationId:c.organizationId,observacao:dto.observacao,items:{create:dto.items}},include:{items:{include:{resource:true}},requestedBy:true}})}
async status(id:string,status:'READY'|'DELIVERED'|'RETURNED'|'CANCELLED',c:OrganizationContext){await this.admin(c);const req=await this.prisma.kidsResourceRequest.findFirst({where:{id,organizationId:c.organizationId}});if(!req)throw new NotFoundException('Solicitação não encontrada');return this.prisma.kidsResourceRequest.update({where:{id},data:{status}})}
async pending(eventId:string,c:OrganizationContext){await this.kidsMember(c);return this.prisma.kidsResourceRequest.findMany({where:{eventId,status:'DELIVERED'},include:{requestedBy:true,items:{include:{resource:true}}}})}
async remind(id:string,c:OrganizationContext){const req=await this.prisma.kidsResourceRequest.findFirst({where:{id,status:'DELIVERED'},include:{event:true,items:{include:{resource:true}}}});if(!req||req.organizationId!==c.organizationId)throw new NotFoundException('Pendência não encontrada');const role=await this.prisma.kidsOperationalRoleAssignment.findFirst({where:{personId:c.personId,campusId:req.event.campusId,role:'WORSHIP_LEADER',ativo:true}});const scheduled=await this.prisma.serviceSchedule.findFirst({where:{personId:c.personId,eventId:req.eventId}});if(!role||!scheduled)throw new ForbiddenException('Somente Líder de Culto escalado pode enviar lembrete');return this.prisma.notification.create({data:{titulo:'Devolução pendente — IBAG Kids',mensagem:`Devolva os recursos: ${req.items.map(i=>i.resource.nome).join(', ')}.`,audience:'PERSON',organizationId:c.organizationId,eventId:req.eventId,recipients:{create:{personId:req.requestedByPersonId}}}})}
private async admin(c:OrganizationContext){const u=await this.prisma.user.findFirst({where:{id:c.userId,organizationId:c.organizationId,...userRoleWhere(['SECRETARY','ADMIN','SUPER_ADMIN'])}});if(!u)throw new ForbiddenException('Somente administração ou almoxarifado pode operar recursos')}
private async kidsMember(c:OrganizationContext){const link=await this.prisma.serviceMembership.findFirst({where:{personId:c.personId,ativo:true,serviceArea:{kidsClasses:{some:{organizationId:c.organizationId}}}}});if(!link)throw new ForbiddenException('Apenas integrantes da IBAG Kids podem solicitar recursos')}
}
